
""" 7600 detector voltage thresholds"""
DETECTOR_WARNING_7600 = 2550 
DETECTOR_REPLACEMENT_7600 = 2600
DETECTOR_MAXIMUM_7600 = 2700

""" 6600 detector voltage thresholds"""
DETECTOR_WARNING_6600 = 2700 
DETECTOR_REPLACEMENT_6600 = 2750 
DETECTOR_MAXIMUM_6600 = 2850 


""" 6600 MS qualifications """
MS_QUALIFICATIONS_ITC00_RESOLUTION = 35000
MS_QUALIFICATIONS_ITC00_INTENSITY = 1*10**6
MS_QUALIFICATIONS_ITC01_RESOLUTION = 30000
MS_QUALIFICATIONS_ITC01_INTENSITY = 1*10**4

MS_QUALIFICATIONS_TOFQC_ITC00 = [MS_QUALIFICATIONS_ITC00_RESOLUTION, MS_QUALIFICATIONS_ITC00_INTENSITY, MS_QUALIFICATIONS_ITC01_RESOLUTION, MS_QUALIFICATIONS_ITC01_INTENSITY]
MS_QUALIFICATIONS_TOF_QC_ITC00 = {'Resolution': MS_QUALIFICATIONS_ITC00_RESOLUTION, 'Intensity sum': MS_QUALIFICATIONS_ITC00_INTENSITY}
MS_QUALIFICATIONS_TOF_QC_ITC01 = {'Resolution': MS_QUALIFICATIONS_ITC01_RESOLUTION, 'Intensity sum': MS_QUALIFICATIONS_ITC01_INTENSITY}


MS_QUALIFICATIONS_HR_RESOLUTION = 25000
MS_QUALIFICATIONS_HR_INTENSITY = 8000
MS_QUALIFICATIONS_HS_RESOLUTION = 16000
MS_QUALIFICATIONS_HS_INTENSITY = 1.5*10**4
MS_QUALIFICATIONS_HSHR_RATIO = 1.5 

MS_QUALIFICATIONS_MSMSQC_ITC00 = [MS_QUALIFICATIONS_HR_RESOLUTION, MS_QUALIFICATIONS_HR_INTENSITY, MS_QUALIFICATIONS_HS_RESOLUTION, MS_QUALIFICATIONS_HS_INTENSITY, MS_QUALIFICATIONS_HSHR_RATIO]
MS_QUALIFICATIONS_MSMS_QC_HS = {'Resolution' : MS_QUALIFICATIONS_HS_RESOLUTION, 'Intensity sum': MS_QUALIFICATIONS_HS_INTENSITY}
MS_QUALIFICATIONS_MSMS_QC_HR = {'Resolution' : MS_QUALIFICATIONS_HR_RESOLUTION, 'Intensity sum': MS_QUALIFICATIONS_HR_INTENSITY, 'Ratio': MS_QUALIFICATIONS_HSHR_RATIO}


MS_QC_TARGETS = [829.53933, 829.53933, 381.24960, 381.24960]
MS_QC_TAGS = ['ITC00', 'ITC01', 'HS', 'HR']